import type { ExportManifest, OutputFormat, PipelineRunResult, PipelineWorkflow } from "../types.js"

function suggestedImporter(format?: OutputFormat): ExportManifest["exportHints"]["suggestedImporter"] {
  switch (format) {
    case "jsonl":
      return "generic-jsonl"
    case "csv":
      return "custom"
    case "markdown":
      return "custom"
    default:
      return "custom"
  }
}

/** Build a portable manifest for downstream training pipelines. */
export function buildExportManifest(
  workflow: PipelineWorkflow,
  result: PipelineRunResult
): ExportManifest {
  const primaryFormat = workflow.output?.format ?? result.artifacts.find((a: { format?: OutputFormat }) => a.format)?.format

  return {
    workflow: {
      name: workflow.name,
      description: workflow.description,
      domain: workflow.domain,
    },
    run: {
      sandboxName: result.sandboxName,
      startedAt: result.startedAt,
      completedAt: result.completedAt,
      status: result.status,
    },
    artifacts: result.artifacts,
    summary: result.summary,
    exportHints: {
      primaryFormat,
      suggestedImporter: suggestedImporter(primaryFormat),
    },
  }
}

/** JSONL rows ready for OpenAI / generic fine-tune importers (metadata wrapper). */
export function toOpenAiFineTuneEnvelope(manifest: ExportManifest): {
  object: "field-pipeline.export"
  version: "0.1"
  manifest: ExportManifest
  notes: string
} {
  return {
    object: "field-pipeline.export",
    version: "0.1",
    manifest,
    notes:
      "Copy dataset.jsonl from sandbox /work/output into your fine-tune upload. " +
      "This envelope is metadata only; artifact bytes live in the sandbox filesystem.",
  }
}

/** Hugging Face dataset card stub from a completed run. */
export function toHuggingFaceDatasetCard(manifest: ExportManifest): string {
  const { workflow, run, artifacts, summary } = manifest
  const artifactList = artifacts.map((a: { path: string; format?: OutputFormat }) => `- \`${a.path}\` (${a.format ?? "unknown"})`).join("\n")

  return [
    "---",
    `title: ${workflow.name}`,
    workflow.domain ? `tags:\n- ${workflow.domain}` : "",
    "---",
    "",
    `# ${workflow.name}`,
    "",
    workflow.description ?? "",
    "",
    "## Provenance",
    "",
    `- Generated by [field-pipeline](https://github.com/deboboy/field-pipeline)`,
    `- Sandbox: \`${run.sandboxName}\``,
    `- Status: ${run.status}`,
    `- Completed: ${run.completedAt ?? "n/a"}`,
    "",
    "## Artifacts",
    "",
    artifactList || "_No artifact paths captured from run logs._",
    "",
    "## Summary",
    "",
    summary ?? "_No SUMMARY.md captured._",
    "",
    "## Upload",
    "",
    "1. Retrieve files from the sandbox output directory",
    "2. Upload to Hugging Face Hub as a dataset",
    "3. Point your training job at the JSONL/CSV paths",
  ]
    .filter(Boolean)
    .join("\n")
}
